# Generated by Django 4.1.5 on 2023-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('bdesc', models.CharField(max_length=1000)),
                ('bprice', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
